---
title: "CollegeAdmit"
author: "Quynh Tran"
date: "April 14, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}



file_path <- '~/compscix415-DataSciencePrinciples/DataSciencePrinciples/data/SingleFamilyResidence2018AlamedaCty.csv'
RealEstate <- read_csv(file = file_path)

file_path <- '~/compscix415-DataSciencePrinciples/DataSciencePrinciples/data/school_zip.csv'
school_zip <- read_csv(file = file_path)

file_path <- '~/compscix415-DataSciencePrinciples/DataSciencePrinciples/data/admit_data_all_uc.csv'
admit_alldata <- read_csv(file = file_path, col_names=TRUE)

file_path <- '~/compscix415-DataSciencePrinciples/DataSciencePrinciples/data/Berkeley.csv'
Berkeley <- read_csv(file = file_path)

file_path <- '~/compscix415-DataSciencePrinciples/DataSciencePrinciples/data/Davis.csv'
Davis<- read_csv(file = file_path, col_names=TRUE)

file_path <- '~/compscix415-DataSciencePrinciples/DataSciencePrinciples/data/Irvine.csv'
Irvine<- read_csv(file = file_path, col_names=TRUE)

file_path <- '~/compscix415-DataSciencePrinciples/DataSciencePrinciples/data/LA.csv'
LA<- read_csv(file = file_path, col_names=TRUE)

file_path <- '~/compscix415-DataSciencePrinciples/DataSciencePrinciples/data/Merced.csv'
Merced<- read_csv(file = file_path, col_names=TRUE)

file_path <- '~/compscix415-DataSciencePrinciples/DataSciencePrinciples/data/Riverside.csv'
Riverside<- read_csv(file = file_path, col_names=TRUE)

file_path <- '~/compscix415-DataSciencePrinciples/DataSciencePrinciples/data/SanDiego.csv'
SanDiego<- read_csv(file = file_path, col_names=TRUE)

file_path <- '~/compscix415-DataSciencePrinciples/DataSciencePrinciples/data/SantaBarb.csv'
SantaBarb<- read_csv(file = file_path, col_names=TRUE)

file_path <- '~/compscix415-DataSciencePrinciples/DataSciencePrinciples/data/SantaCruz.csv'
SantaCruz<- read_csv(file = file_path, col_names=TRUE)

admit_alldata
Berkeley
school_zip

```
  
  
```{r}


library (dplyr)

admit_data <- spread(data=admit_alldata, key="Measure Names", value="Measure Values") %>% mutate(AdmitStat=adm/app, Campus="All", Year=2017)

Berkeley_admit <- spread(data=Berkeley, key="Measure Names", value="Measure Values") %>% mutate(AdmitStat=adm/app, Campus="Berkeley", Year=2017) 

Davis_admit <- spread(data=Davis, key="Measure Names", value="Measure Values") %>% mutate(AdmitStat=adm/app, Campus="Davis", Year=2017) 

Irvine_admit <- spread(data=Irvine, key="Measure Names", value="Measure Values") %>% mutate(AdmitStat=adm/app, Campus="Irvine", Year=2017) 

LA_admit <- spread(data=LA, key="Measure Names", value="Measure Values") %>% mutate(AdmitStat=adm/app, Campus="LosAng", Year=2017) 

Merced_admit <- spread(data=Merced, key="Measure Names", value="Measure Values") %>% mutate(AdmitStat=adm/app, Campus="Merced", Year=2017) 

Riverside_admit <- spread(data=Riverside, key="Measure Names", value="Measure Values") %>% mutate(AdmitStat=adm/app, Campus="Riverside", Year=2017) 

SanDiego_admit <- spread(data=SanDiego, key="Measure Names", value="Measure Values") %>% mutate(AdmitStat=adm/app, Campus="SanDiego", Year=2017) 

SantaBarb_admit <- spread(SantaBarb, key="Measure Names", value="Measure Values") %>% mutate(AdmitStat=adm/app, Campus="SantaBarb", Year=2017) 

SantaCruz_admit <- spread(data=SantaCruz, key="Measure Names", value="Measure Values") %>% mutate(AdmitStat=adm/app, Campus="SantaCruz", Year=2017) 


admit_data
Berkeley_admit
Davis_admit
Irvine_admit
LA_admit
Merced_admit
Riverside_admit
SanDiego_admit
SantaBarb_admit
SantaCruz_admit

```
```{r}
total <-rbind (Berkeley_admit, Davis_admit, Irvine_admit, LA_admit, Merced_admit, Riverside_admit, SanDiego_admit, SantaBarb_admit, SantaCruz_admit)

total

```

```{r}
zipped <- merge (total, school_zip, "Calculation1") 
zipped

```



```{r}
names(zipped)[1]<-"SchoolID"
names(zipped)[3]<-"County"
names(zipped)[5]<-"Race"

zipped
```

```{r}
All_zip <- merge (zipped, RealEstate,"Zipcode") 

names(All_zip)[5]<-"School"
names(All_zip)[17]<-"Jan2018"
names(All_zip)[18]<-"Feb2018"
names(All_zip)[19]<-"March2018"

All_zip

```

```{r}
##All_zip <- mutate(data=All_zip, AvgHomePrice2018=(Jan2018+Feb2018+March2018)/3)

All_zip
```

library (ISLR)
library (ROCR)
library (rpart)
library (tidyverse)
library (broom)
library(partykit)

```{r}

##ggplot(df, aes(x=weight)) + geom_histogram()    
  
```




```{r}
  ggplot(data=All_zip)+
    geom_point(mapping= aes(x=School, y=AdmitStat, color=Race)) +
    facet_wrap(~ School, nrow = 2)+
  labs (y="All campus admissions", x='2017')
    
ggplot(All_zip, aes(x=AdmitStat))+
    geom_histogram () +
coord_flip() +
  labs (y="All campus admissions 2017")
```
```{r}



 ggplot(data=Berkeley_admit)+
    geom_point(mapping= aes(x=School, y=AdmitStat, color=Race))+
    facet_wrap(~ City, nrow = 2) +
 labs(y= "Berkeley admissions", x="2017")
 
 ggplot(Berkeley_admit, aes(x=AdmitStat))+
    geom_histogram () +
coord_flip() +
   labs (y="Berkeley admissions 2017")
 
 ggplot(data=Davis_admit)+
    geom_point(mapping= aes(x=School, y=AdmitStat, color=Race))+
    facet_wrap(~ City, nrow = 2) +
 labs(y= "Davis admissions", x="2017")
 
 ggplot(Davis_admit, aes(x=AdmitStat))+
    geom_histogram () +
coord_flip()+
   labs (y="Davis admissions 2017")
 
 ggplot(data=Irvine_admit)+
    geom_point(mapping= aes(x=School, y=AdmitStat, color=Race))+
    facet_wrap(~ City, nrow = 2) +
 labs(y= "Irvine admissions", x="2017")
 
 ggplot(Irvine_admit, aes(x=AdmitStat))+
    geom_histogram () +
coord_flip() +
   labs (y="Irvine admissions 2017")
 
 ggplot(data=LA_admit)+
    geom_point(mapping= aes(x=School, y=AdmitStat, color=Race))+
    facet_wrap(~ City, nrow = 2) +
 labs(y= "Los Angeles admissions", x="2017")
 
 ggplot(LA_admit, aes(x=AdmitStat))+
    geom_histogram () +
coord_flip()+
   labs (y="LA admissions 2017")
 
 ggplot(data=Merced_admit)+
    geom_point(mapping= aes(x=School, y=AdmitStat, color=Race))+
    facet_wrap(~ City, nrow = 2) +
 labs(y= "Merced admissions", x="2017")
 
 ggplot(Merced_admit, aes(x=AdmitStat))+
    geom_histogram () +
coord_flip() +
   labs (y="Merced admissions 2017")
 
 ggplot(data=Riverside_admit)+
    geom_point(mapping= aes(x=School, y=AdmitStat, color=Race))+
    facet_wrap(~ City, nrow = 2) +
 labs(y= "Riverside admissions", x="2017")
 
 ggplot(Riverside_admit, aes(x=AdmitStat))+
    geom_histogram () +
coord_flip() +
   labs (y="Riverside admissions 2017")
 
 ggplot(data=SanDiego_admit)+
    geom_point(mapping= aes(x=School, y=AdmitStat, color=Race))+
    facet_wrap(~ City, nrow = 2) +
 labs(y= "San Diego admissions", x="2017")
 
 ggplot(SanDiego_admit, aes(x=AdmitStat))+
    geom_histogram () +
coord_flip() +
   labs (y="San Diego admissions 2017")
 
 ggplot(data=SantaBarb_admit)+
    geom_point(mapping= aes(x=School, y=AdmitStat, color=Race))+
    facet_wrap(~ City, nrow = 2) +
 labs(y= "SantaBarb admissions", x="2017")
 
 ggplot(SantaBarb_admit, aes(x=AdmitStat))+
    geom_histogram () +
coord_flip() +
   labs (y="Santa Barbara admissions 2017")
 
 ggplot(data=SantaCruz_admit)+
    geom_point(mapping= aes(x=School, y=AdmitStat, color=Race))+
    facet_wrap(~ City, nrow = 2) +
 labs(y= "SantaCruz admissions", x="2017")
 
 ggplot(SantaCruz_admit, aes(x=AdmitStat))+
    geom_histogram () +
coord_flip() +
   labs (y="Santa Cruz admissions 2017")
 
```
```{r}
tree_modAll <- rpart(AdmitStat ~ City + Race, data = All_campus) 
plot(as.party(tree_modAll))

tree_modBerkeley <- rpart(AdmitStat ~ City + Race, data = Berkeley_admit) 
plot(as.party(tree_modBerkeley))

tree_modDavis <- rpart(AdmitStat ~ City + Race, data = Davis_admit) 
plot(as.party(tree_modDavis))

tree_modIrvine <- rpart(AdmitStat ~ City + Race, data = Irvine_admit) 
plot(as.party(tree_modIrvine))

tree_modLA <- rpart(AdmitStat ~ City + Race, data = LA_admit) 
plot(as.party(tree_modLA))

tree_modMerced <- rpart(AdmitStat ~ City + Race, data = Merced_admit) 
plot(as.party(tree_modMerced))

tree_modRiverside <- rpart(AdmitStat ~ City + Race, data = Riverside_admit) 
plot(as.party(tree_modRiverside))

tree_modSanDiego <- rpart(AdmitStat ~ City + Race, data = SanDiego_admit) 
plot(as.party(tree_modSanDiego))

tree_modSantaBarb <- rpart(AdmitStat ~ City + Race, data = SantaBarb_admit) 
plot(as.party(tree_modSantaBarb))

tree_modSantaCruz <- rpart(AdmitStat ~ City + Race, data = SantaCruz_admit) 
plot(as.party(tree_modSantaCruz))


```


```{r}
AdmittanceAll <- lm(AdmitStat ~ City + Race, data = All_campus)
# take a look at the features and coefficients
tidy(AdmittanceAll)

AdmittanceBerk <- lm(AdmitStat ~ City + Race, data = Berkeley_admit)
# take a look at the features and coefficients
tidy(AdmittanceBerk)

AdmittanceDavis<- lm(AdmitStat ~ City + Race, data = Davis_admit)
# take a look at the features and coefficients
tidy(AdmittanceDavis)

AdmittanceIrvine <- lm(AdmitStat ~ City + Race, data = Irvine_admit)
# take a look at the features and coefficients
tidy(AdmittanceBerk)

AdmittanceLA <- lm(AdmitStat ~ City + Race, data = LA_admit)
# take a look at the features and coefficients
tidy(AdmittanceLA)

AdmittanceMerced <- lm(AdmitStat ~ City + Race, data = Merced_admit)
# take a look at the features and coefficients
tidy(AdmittanceMerced)

AdmittanceRiverside<- lm(AdmitStat ~ City + Race, data = Riverside_admit)
# take a look at the features and coefficients
tidy(AdmittanceRiverside)

AdmittanceSanDiego <- lm(AdmitStat ~ City + Race, data = SanDiego_admit)
# take a look at the features and coefficients
tidy(AdmittanceSanDiego)

AdmittanceSantaBarb <- lm(AdmitStat ~ City + Race, data = SantaBarb_admit)
# take a look at the features and coefficients
tidy(AdmittanceSantaBarb)

AdmittanceSantaCruz <- lm(AdmitStat ~ City + Race, data = SantaCruz_admit)
# take a look at the features and coefficients
tidy(AdmittanceSantaCruz)
```







